spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: adminBase
    url: ${DEV_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/admin_base?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${DEV_DATASOURCE_USERNAME:root}
    password: ${DEV_DATASOURCE_PASSWORD:}
  data:
    redis:
      database: ${DEV_REDIS_DATABASE:0}
      host: ${DEV_REDIS_HOST:127.0.0.1}
      port: ${DEV_REDIS_PORT:6379}
      password: ${DEV_REDIS_PASSWORD:}
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
sysconfig:
  captchaType: math
  uploadPath: /home/uploadPath
  downloadPath: /home/download
  localStore: /home/local
  resourcePrefix: /profile