spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${TEST_DATASOURCE_URL:jdbc:mysql://192.168.3.3:3306/mark?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${TEST_DATASOURCE_USERNAME:root}
    password: ${TEST_DATASOURCE_PASSWORD:hjdz@10086}
  data:
    redis:
      host: ${TEST_REDIS_HOST:192.168.3.3}
      port: ${TEST_REDIS_PORT:6379}
      password: ${TEST_REDIS_PASSWORD:hjdz@10086}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
admin:
  auth:
    mode: jwt
